title: Daniel Ziorli # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  3rd year software engineer student with a minor in statistics at the University of Guelph.
  <br><br>
  Currently working at TD Labs as a solution developer.
  <br><br>
  <a href="https://www.github.com/daniel-ziorli">Take a look at my Github</a>
  <a href="https://www.linkedin.com/in/daniel-ziorli-2443bb164/">Linkedin Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
